version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run lint
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd services/web && npm ci
            - run: cd services/web && npm run test
  simple-lint-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: cd services/web && npm ci
            - run: npm run lint
            - run: cd services/web && npm run test

workflows:
  build-and-test:
    jobs:
      - lint
      - test
  simple-build-and-test:
    jobs:
      - simple-lint-test
